spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${LOCAL_DATASOURCE_URL}
    username: ${LOCAL_DATASOURCE_USERNAME}
    password: ${LOCAL_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.jamjam.bookjeok.domains

server:
  port: 8080

tosspayemnts:
  wiget-secret-key: ${WIDGET_SECRET_KEY}
  api-secret-key: ${API_SECRET_KEY}

naver:
  book-client-api: ${BOOK_CLIENT_ID}
  book-secret-key: ${BOOK_CLIENT_KEY}
